server:
    port: 8080
    servlet:
        session:
            timeout: 43200m      # 60m * 24h * 30d
spring:
    servlet:
        encoding:
            force-response: true

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:mysql://localhost:3306/example
        username: sa
        password:
    jpa:
        show-sql: true
        database: mysql
        hibernate.ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
